### ISSUE TITLE
reading large compressed file with maor and press ESC to quit cause cli freeze

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#172] opened 2023-12-18 13:11 UTC
Hi Johan,

On the latest moar version CLI freezes when reading a large compressed file and pipes with ack for certain keywords. you can see in below screenshot after pressing ESC or quit key nothing happening and it stuck in prompt

<img width="411" alt="image" src="https://github.com/walles/moar/assets/11479557/8b9e14ce-4d4a-4cbf-88e1-ecb1677aa0e0">

**Comment by ciscohack** [comment] 2023-12-18 13:17
I see the issue is happening with the alias "alias mo='ct moar -style=catppuccin-macchiato'"

ct is a syntax highlighter tool .. more details are in below reference link below. Can you please fix this.
https://github.com/hSaria/ChromaTerm

**Comment by walles** [comment] 2023-12-19 13:59
Since `moar`'s output is going to a pipe, `moar` will just pass its input file right through.

The reason `ack` isn't finding anything is that it's trying to search compressed input.

Using `cat` instead of `moar` would get you the same result.

**Comment by ciscohack** [comment] 2023-12-19 17:43
@walles Thanks for the comment. ok, the cat does not support compressed files so not tried but if that is the case then pipe option cli stuck seems not the right thing.  also noticed while search in moar also freeze cli for few second if you typed the keyword incorrectly and keyword not present in searched file

**Comment by walles** [comment] 2023-12-21 09:49
To search a file from the command line (`moar` not involved):

```bash
gunzip -c cluster_trace.log.gz | ack 'CRIT'
```

If you have problems when searching by pressing <kbd>/</kbd> inside of `moar`, then:
1. How large was the input?
2. Was it compressed?

**Comment by ciscohack** [comment] 2023-12-21 19:33
> To search a gzipped file from the command line (`moar` not involved):
> 
> ```shell
> gunzip -c cluster_trace.log.gz | ack 'CRIT'
> ```
> 
> If you have problems when searching by pressing / inside of `moar`, then:
> 
> 1. How large was the input?
> 2. Was it compressed?

Ok, I thought since Moar is able to reach compressed files without extracting file.. it is able to grep keywords also but thanks for clarification.


Yes file is very large 1M lines if log..compressed and uncompressed but freeze with / search for few sec in case of wrong typo or sometime with correct keyword

**Comment by walles** [comment] 2023-12-28 18:08
Can you do this and post the result?

```
gunzip -c cluster_trace.log.gz | wc 
```

This will tell me how many lines and chars there are in your log file.

**Comment by ciscohack** [comment] 2023-12-28 20:32
> Can you do this and post the result?
> 
> ```
> gunzip -c cluster_trace.log.gz | wc 
> ```
> 
> This will tell me how many lines and chars there are in your log file.

This file is still small but I used log file even bigger in size... Here is the result of your requested command

 gunzip -c cluster_trace.log.gz | wc                                       
   7866  103841  885450

here is bigger file size info

moar sw-techsupport | wc      
 925120 4953043 46990036

**Comment by walles** [comment] 2023-12-28 20:34
Cool, so about 1M lines, 5M words and 50MB size.

**Comment by ciscohack** [comment] 2023-12-28 20:38
@walles  I have noticed one more issue if you use chromaterm (https://github.com/hSaria/ChromaTerm) and create alias like

mo = "ct moar"  and then if run mo <file_name> and pipe anything to this example mo <file_name> | wc ..it freeze the cli or tab and ctrl + c/z/d nothing works ..... I suggested please fix this also

**Comment by walles** [comment] 2023-12-29 16:30
> @walles I have noticed one more issue if you use chromaterm (https://github.com/hSaria/ChromaTerm) and create alias like
> 
> mo = "ct moar" and then if run mo <file_name> and pipe anything to this example mo <file_name> | wc ..it freeze the cli or tab and ctrl + c/z/d nothing works ..... I suggested please fix this also

Please open a separate issue for this.

**Comment by ciscohack** [comment] 2023-12-29 16:54
> > @walles I have noticed one more issue if you use chromaterm (https://github.com/hSaria/ChromaTerm) and create alias like
> > mo = "ct moar" and then if run mo <file_name> and pipe anything to this example mo <file_name> | wc ..it freeze the cli or tab and ctrl + c/z/d nothing works ..... I suggested please fix this also
> 
> Please open a separate issue for this.

Issue mentioned in this ticket is same right ?

**Comment by walles** [comment] 2023-12-29 17:04
There are at least three separate issues reported in here:
* search in moar also freeze cli for few second if you typed the keyword incorrectly and keyword not present in searched file
* `moar` won't decompress input files if used in a pipeline
* `ct moar | wc` hangs

Kindly open separate issues for these.

**Comment by ciscohack** [comment] 2023-12-29 18:34
Sure thanks Opened 3 tickets as suggested. Hope you are now aware of all the reported scenarios... I am travelling so will be unable.

**Comment by walles** [comment] 2023-12-31 12:10
> On the latest moar version CLI freezes when reading a large compressed file and pipes with ack for certain keywords. you can see in below screenshot after pressing ESC or quit key nothing happening and it stuck in prompt
> <img alt="image" width="411" src="https://private-user-images.githubusercontent.com/11479557/291293438-8b9e14ce-4d4a-4cbf-88e1-ecb1677aa0e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMjQyNTMsIm5iZiI6MTcwNDAyMzk1MywicGF0aCI6Ii8xMTQ3OTU1Ny8yOTEyOTM0MzgtOGI5ZTE0Y2UtNGQ0YS00Y2JmLTg4ZTEtZWNiMTY3N2FhMGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDExNTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1OTg0NjcwNmNmYTM2Y2I3YTNiMjVlYjU3ODI5NGU3OGVhNmIyOTVmZDlmNzkwMjc2Y2E1MWM0NzhlYjgyNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mEyIIsDpQBJVrNoXIkGJKiuWmo-337A8QWEH9sMwO5Q">

Assuming this is with `ct` enabled, the CLI freeze is a duplicate of #176.

**Closed by walles** 2023-12-31 12:10 UTC
