### ISSUE TITLE
Backspace key not delete the character

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#55] opened 2021-05-09 07:11 UTC
Hi Expert,

In moar pager if accidentally type wrong search keyword and try to delete through backspace or delete key. it's not deleting the character instead every delete key press it create ? symbol. can we fix it and how do we upgrade the moar app for future release. do i need manual download and replace all time. can we add syntax highlighting support in moar app in future

**Comment by walles** [comment] 2021-05-09 11:12
Hello @ciscohack, thanks for using `moar` and reporting issues!

> In moar pager if accidentally type wrong search keyword and try to delete through backspace or delete key. it's not deleting the character instead every delete key press it create ? symbol. can we fix it

To figure out why it doesn't work for you I'll need some information about your system and how you're using `moar`:

1. What version of `moar` are you running? Please do `moar --version` and post the output here.
2. What platform are you on? Linux, macOS, something else? If Linux, which distro / release?
3. What are your terminal settings? Try `echo $TERM` and post the output here.
4. How are you calling `moar`? Please tell me the exact command you use to start viewing your not-syntax-highlighted file.

Note that this works for me on my machine, so I will need more info from you to be able to say something here.

> how do we upgrade the moar app for future release. do i need manual download and replace all time

For now I'm not aware of `moar` being packaged for any platform, but once I know what platform you're on I might be able to give you a better answer here, see questions above.

> can we add syntax highlighting support in moar app in future

Syntax highlighting is built-in since version `1.2`.

Let's get back to this after I know what version you're on (question 1 above).

**Comment by ciscohack** [comment] 2021-05-09 12:25
Hi @walles 

Thanks for quick response. I am running moar on macOS Big Sur 11.3.1 version. I saw in GitHub page you mentioned that it support chroma based syntax highlighter but due to some reason it's not working for me with BAT tool. Here are the requested data .

[praveri@ ~]$ moar --version
v1.5.0
[praveri@ ~]$ echo $TERM
iterm-256color

OS: macOS 11.3.1 20E241 x86_64
Host: MacBookPro16,1
Kernel: 20.4.0
Terminal App: Iterm2


Here  color highlighted with less pager
![image](https://user-images.githubusercontent.com/11479557/117572218-7ade6680-b0ef-11eb-93ab-ee7bc65214e9.png)

Here color not highlighted with moar pager

![image](https://user-images.githubusercontent.com/11479557/117572240-a06b7000-b0ef-11eb-9bf6-8254521fde49.png)

**Comment by ciscohack** [comment] 2021-05-09 12:29
See in this screenshot i am trying to delete and instead of delete it's add ? mark 

![image](https://user-images.githubusercontent.com/11479557/117572352-27204d00-b0f0-11eb-9164-6289d986ae7c.png)

**Comment by walles** [comment] 2021-05-09 13:56
What is the exact command line you're using to invoke `moar`?

**Comment by walles** [comment] 2021-05-09 13:57
Actually, I think the missing highlighting is because `moar` isn't getting any color codes.

If `bat` sends color codes to `less` but not to `moar`, that would totally explain the coloring part of your questions.

**Comment by walles** [comment] 2021-05-09 13:58
Chroma only comes into play if you do `moar flupp.c` for example, then you'll get your C file in glorious color.

**Comment by ciscohack** [comment] 2021-05-09 13:59
i used moar and less command to invoke in above screenshot. yes i do use BAT in general. I would appreciate if you make moar compatible with BAT also in future update. But in this case i used moar command only.

Delete key issue i corrected with keybinding.

**Comment by ciscohack** [comment] 2021-05-09 14:01
> Chroma only comes into play if you do `moar flupp.c` for example, then you'll get your C file in glorious color.

![image](https://user-images.githubusercontent.com/11479557/117574901-0a3e4680-b0fd-11eb-9733-091c98581368.png)

I understand your point but can we do color for logs and txt files also like above i invoke  less pager and still see colors for someof keyward i added in my iterm2 for trigger

**Comment by ciscohack** [comment] 2021-05-09 14:02
I forgot to thanks you for such a amazing pager. I really loved it and i can see lot of great potential in it. Thanks once again for this great work!

**Comment by walles** [comment] 2021-05-09 14:03
So what you're saying is:
* `less 20210303-200140926_PI-show_tech_support.txt` -> Color
* `moar 20210303-200140926_PI-show_tech_support.txt` -> No color

Is this correct?

**Comment by ciscohack** [comment] 2021-05-09 14:50
> So what you're saying is:
> 
> * `less 20210303-200140926_PID-show_tech_support.txt` -> Color
> * `moar 20210303-200140926_PID-show_tech_support.txt` -> No color
> 
> Is this correct?
> 
> Can you try `cat 20210303-200140926_PID-show_tech_support.txt` as well? Do you get color from that?

Yes that is what i did in above screenshot you can see. Basically in iterm2 there is a feature to trigger color highlight for keywards i defined and it's working well with less but completely un color in moar. i used pager and log reading a lot and color highlight helps me to read the file faster

**Comment by walles** [comment] 2021-05-09 15:05
So `cat` gets you color?

Is this what you're using for highlighting?
https://iterm2.com/documentation-triggers.html

**Comment by ciscohack** [comment] 2021-05-09 15:16
> So `cat` gets you color?
> 
> Is this what you're using for highlighting?
> https://iterm2.com/documentation-triggers.html

Yes this is the method i am using and yes cat also give me color. but now i bind cat with BAT tool. but in all condition i get the colors except moar pager

**Comment by walles** [comment] 2021-05-09 17:29
`moar` is using [alternate screen mode](https://terminalguide.namepad.de/mode/p47/), that could be the cause, but I'd need to experiment to verify.

I think that `less` does not use alternate screen mode.

**Comment by ciscohack** [comment] 2021-05-09 18:16
> `moar` is using [alternate screen mode](https://terminalguide.namepad.de/mode/p47/), that could be the cause, but I'd need to experiment to verify.
> 
> I think that `less` does not use alternate screen mode.

Leta try and make this tool even better and compatible with more tools

**Comment by ciscohack** [comment] 2021-05-10 11:02
@walles Hello my friend, i just wanted to understand in moar pager text selection not work? if yes why can we add in future this option also. Now i opened one txt based file with moar and try to grab small chunk of text but selection is not working just noticed

**Comment by ciscohack** [comment] 2021-05-10 11:56
> Mouse selection is #53.
> 
> Given a number of things you've brought up above my suggestion is this:
> 
> * `moar` should accept a `-compat` command line switch which makes screen handling work as much as possible like `less`
> * `moar` should read defaults from the `MOAR` environment variable
> 
> That should cover your (and likely many other people's) needs, but still allow mouse scrolling to work out of the box (which isn't necessarily the case with `less`).

First again thanks for the prompt answer and help . i tried moar  -compat <filename. indeed this solve selection problem but then with this option. I lost moar other powerful features like search-while type and highlight the searched keyword

**Comment by ciscohack** [comment] 2021-05-10 18:42
> > i tried moar -compat <filename
> 
> `-compat` doesn't exist.
> 
> If it _was_ implemented I think it would be a good way to solve both mouse select and your highlighting issue.

Seems i am not getting now. i able to invoke mouse though -compat switch but this breaking other functionality. Anyway we should work on our documentation also in future. to know more in depth of your amazing tool. Though i am missing some of my daily used feature but still now i am using moar as my daily driver. I have big hope you will bring many stuff in future or compatibility with other great tool like BAT as pager option

**Comment by walles** [comment] 2021-05-14 06:35
Regarding iTerm's highlighting, I just tried it with iTerm 3.4.6, and it works in `moar` when I try it.

Screenshot is from `moar` 1.6.0. What iTerm version and settings did you use when iTerm's highlighting did *not* work for you?

<img width="542" alt="moar-with-highlight" src="https://user-images.githubusercontent.com/158201/118231086-e416fe80-b48e-11eb-9430-412d545a0f12.png">

<img width="1036" alt="iterm-triggers" src="https://user-images.githubusercontent.com/158201/118231124-f002c080-b48e-11eb-96a6-726ed5b85ed5.png">

**Comment by ciscohack** [comment] 2021-05-14 08:00
> Regarding iTerm's highlighting, I just tried it with iTerm 3.4.6, and it works in `moar` when I try it.
> 
> Screenshot is from `moar` 1.6.0. What iTerm version and settings did you use when iTerm's highlighting did _not_ work for you?
> 
> <img alt="moar-with-highlight" width="542" src="https://user-images.githubusercontent.com/158201/118231086-e416fe80-b48e-11eb-9430-412d545a0f12.png">
> 
> <img alt="iterm-triggers" width="1036" src="https://user-images.githubusercontent.com/158201/118231124-f002c080-b48e-11eb-96a6-726ed5b85ed5.png">

Thanks @walles for keep trying for improvement. I am sharing with you my iterm2 profile setting with color highlight trigger. try with this. it will not work
[com.googlecode.iterm2.zip](https://github.com/walles/moar/files/6477373/com.googlecode.iterm2.zip)

**Comment by walles** [comment] 2021-05-14 08:04
Can you just make a screenshot of your triggers config pane like I did?

**Comment by walles** [comment] 2021-05-14 08:05
And post your iTerm version?

**Comment by ciscohack** [comment] 2021-05-14 08:11
> And post your iTerm version?

Here is my iterm2 version screenshot. See here point is your pager is working fine with syntax highlight for programming  language and i tested. But as i mentioned i use iterm2 tigger to highlight syslog and any other log files and thats the point moar failed to do the job.

![image](https://user-images.githubusercontent.com/11479557/118241519-dfb40b00-b4b9-11eb-8551-0f536314dbe9.png)

**Comment by ciscohack** [comment] 2021-05-14 08:12
Yo please load my shared profile. you will get more clarity and do not open any programming file. just open any log file

**Comment by walles** [comment] 2021-05-14 08:26
So I loaded your profile, ran `cat`, and typed `Encryption hardware device` as in [your example](https://github.com/walles/moar/issues/55#issuecomment-835796790).

But it's not highlighted by iTerm. From your description I thought this should be highlighted by iTerm.

What exact text could I type in my terminal to get it highlighted using your settings?

**Is it iTerm, `LESSFILTER`, `bat` or something else entirely (what?) that provides you with colors in your example?**

Without knowing this it is impossible for me to know why it doesn't work in `moar`.

<img width="583" alt="not-highlighted" src="https://user-images.githubusercontent.com/158201/118243589-e2553700-b49e-11eb-8372-70972247e613.png">

**Comment by ciscohack** [comment] 2021-05-14 08:36
> So I loaded your profile, ran `cat`, and typed `Encryption hardware device` as in [your example](https://github.com/walles/moar/issues/55#issuecomment-835796790).
> 
> But it's not highlighted by iTerm. From your description I thought this should be highlighted by iTerm.
> 
> What exact text could I type in my terminal to get it highlighted using your settings?
> 
> **Is it iTerm, `LESSFILTER`, `bat` or something else entirely (what?) that provides you with colors in your example?**
> 
> Without knowing this it is impossible for me to know why it doesn't work in `moar`.
> 
> <img alt="not-highlighted" width="583" src="https://user-images.githubusercontent.com/158201/118243589-e2553700-b49e-11eb-8372-70972247e613.png">

copy this log in any text file and save then open in terminal .. it will show color


WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.
WARNING: Failover is enabled but standby IP address is not configured for this interface.

**Comment by walles** [comment] 2021-05-14 08:45
Works fine both with `moar` and `cat`.

Can you repro these screenshots?

If you do, can you screenshot the full windows, including borders? Higher up in this thread you only posted the middle of the windows so it's impossible to see what program it is that is showing.

<img width="926" alt="cat-with-highlight" src="https://user-images.githubusercontent.com/158201/118245538-3e20bf80-b4a1-11eb-8d39-e9504cb46bd8.png">
<img width="926" alt="moar-with-highlight" src="https://user-images.githubusercontent.com/158201/118245548-40831980-b4a1-11eb-9a15-82024c86bc31.png">

**Comment by ciscohack** [comment] 2021-05-14 08:49
> Works fine both with `moar` and `cat`.
> 
> Can you repro these screenshots?
> 
> If you do, can you screenshot the full windows, including borders? Higher up in this thread you only posted the middle of the windows so it's impossible to see what program it is that is showing.
> 
> <img alt="cat-with-highlight" width="926" src="https://user-images.githubusercontent.com/158201/118245538-3e20bf80-b4a1-11eb-8d39-e9504cb46bd8.png">
> 
> <img alt="moar-with-highlight" width="926" src="https://user-images.githubusercontent.com/158201/118245548-40831980-b4a1-11eb-9a15-82024c86bc31.png">

It's small text so moar not throwing error. if file size grow a bit then it will throw error basically it's get disabled but iterm2 nightly build what i have. I opened a case with them also. Try this log file

[18-36.log](https://github.com/walles/moar/files/6477652/18-36.log)

**Comment by walles** [comment] 2021-05-14 08:52
Also works in `moar`.

Can you please post a screenshot of what it looks like when *you* try this file in `moar`?

<img width="926" alt="18-36-with-colors" src="https://user-images.githubusercontent.com/158201/118246522-580ed200-b4a2-11eb-9cdd-c3825855c15a.png">

**Comment by ciscohack** [comment] 2021-05-14 09:08
> Also works in `moar`.
> 
> Can you please post a screenshot of what it looks like when _you_ try this file in `moar`?
> 
> <img alt="18-36-with-colors" width="926" src="https://user-images.githubusercontent.com/158201/118246522-580ed200-b4a2-11eb-9cdd-c3825855c15a.png">

Just installed the iterm2 version you have which is global public build. I am on iterm2 nightly build which has some feature not yet added in public build. So with public build i am also not facing issue.  there is a feature in nightly built which detect interactive app like moar/broot tool and if it see the tool and terminal slowness . it disabled the trigger. So seems issue not with moar Thanks.

**Comment by walles** [comment] 2021-05-14 12:53
Lots of sub issues here, let me try to sum this up:
* ✅ <kbd>backspace</kbd> doesn't work: You figured this out yourself, and [since `moar` `v1.6.0` this can now be tracked down using the `-trace` command line option](https://github.com/walles/moar/commit/2b1e87b8ac3fce4c8a7f57ad1b00bfa3503a278a)
* ✅ Highlighting broken: This turned out [not to be `moar`'s fault](https://github.com/walles/moar/issues/55#issuecomment-841118576)
* Packaging / updating: I moved this into #63 
* Mouse copying: Should be covered by #53 

I'll close this issue now in favor of #53 and #63, please continue discussions about those topics in there.

In case I missed something in the above list, please open new tickets, with one issue in each if possible!

**Closed by walles** 2021-05-14 12:53 UTC

**Comment by ciscohack** [comment] 2021-05-14 13:28
> Lots of sub issues here, let me try to sum this up:
> 
> * ✅ backspace doesn't work: You figured this out yourself, and [since `moar` `v1.6.0` this can now be tracked down using the `-trace` command line option](https://github.com/walles/moar/commit/2b1e87b8ac3fce4c8a7f57ad1b00bfa3503a278a)
> * ✅ Highlighting broken: This turned out [not to be `moar`'s fault](https://github.com/walles/moar/issues/55#issuecomment-841118576)
> * Packaging / updating: I moved this into #63
> * Mouse copying: Should be covered by #53
> 
> I'll close this issue now in favor of #53 and #63, please continue discussions about those topics in there.
> 
> In case I missed something in the above list, please open new tickets, with one issue in each if possible!

Thanks for all your support on this ..looking forward for new features and enhancement

**Comment by walles** [comment] 2021-05-14 13:56
Just out of curiosity, where did you find `moar` in the first place?

**Comment by ciscohack** [comment] 2021-05-14 17:50
> Just out of curiosity, where did you find `moar` in the first place? How did you hear about it?

I use BAT tool and part of that community. So i put a feature request there and one person told me the feature i am looking is in moar tool and immediately i installed. You should maintain it better way. your tool is very early stage and no man page . But i am sure you will soon come up with many cool stuff
