### ISSUE TITLE
Slow response in latest moar

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#218] opened 2024-06-28 16:28 UTC
I feel Moar is lagging with inputting any search query or sometimes opening log files. I am running the latest maor 1.24.4 version on macOS 14.4 code.

**Comment by walles** [comment] 2024-09-07 19:26
Is this with or without `ct`?

If it is without `ct`:
* Please run `moar` with `--trace`
* Reproduce the slow search
* `q` to exit `moar`
* `moar` should now produce trace logs in your terminal
* Please post the trace logs in this ticket.

**Comment by ciscohack** [comment] 2024-09-07 19:39
@walles all log above i shared with you is with ct and --trace only ..without ct moar is working fine

**Comment by walles** [comment] 2024-09-08 05:28
Then I guess this is a duplicate of the `ct` issues in #241.

I'll close this as well since I can't help with `ct`.

**Closed by walles** 2024-09-08 05:28 UTC
