### ISSUE TITLE
error rendering output of tree

### ISSUE THREAD

**Issue by nkh** [walles/moar#101] opened 2022-08-06 06:41 UTC
$> tree | moar

spurious '??' are displayed among the tree lines

**Comment by walles** [comment] 2022-08-07 10:04
`moar` expects its input to be UTF-8 encoded text.

Unprintable / invalid characters are rendered as `?` (see below).

You have two options:
* Resolve the root cause by making `tree` output valid and printable UTF-8 only
* Try working around the problem using `--render-unprintable whitespace`

I will consider documenting this better before closing this issue.

https://github.com/walles/moar/blob/fdb520ce13c1c825e5465e35a3713d135e320df3/m/ansiTokenizer.go#L134-L153

**Closed** 2022-08-07 17:27 UTC
