### ISSUE TITLE
Mistranslations of file reference resulting in broken characters

### ISSUE THREAD

**Issue by excited-bore** [walles/moar#133] opened 2023-04-29 12:34 UTC
![moar_bug](https://user-images.githubusercontent.com/31372378/235302801-1d1ced55-655c-4d64-ac04-7cb64be12c71.png)
moar - less
I've seen other cases, but here it *seems* to be related to referencing files from the users system

**Comment by walles** [comment] 2023-04-30 13:29
Duplicate of this one: https://github.com/walles/moar/issues/131

**Closed by walles** 2023-04-30 13:29 UTC

**Comment by walles** [comment] 2023-05-03 18:09
Fix released: https://github.com/walles/moar/releases/tag/v1.14.0
