### ISSUE TITLE
moar won't decompress input files if used in a pipeline 

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#177] opened 2023-12-29 18:33 UTC
If we use moar with a combination of ct tool (https://github.com/hSaria/ChromaTerm), pipe it won't work and freeze the CLI

It would be good if this problem could be addressed

**Comment by walles** [comment] 2023-12-31 12:07
Sounds like a duplicate of #176.

**Closed by walles** 2023-12-31 12:07 UTC

**Comment by walles** [comment] 2024-01-11 10:56
Decompressing files as `moar something.gz | wc -l` works now.
