### ISSUE TITLE
Feature request for pattern search like VIM

### ISSUE THREAD

**Issue by ciscohack** [walles/moar#72] opened 2021-10-02 05:44 UTC
Hi Team,

Can we have pattern search feature in moar like we have in vim where we use :g/pattern to match the keyword and list all the lines match to search pattern then we use vim jump feature to jump on the matched line

Second issue i have noticed when i try to search any keyword in moar by click / the search box appear then if any keyword which i have selected and wants to paste. i am not able to do it. I have to type the search keyword all time. Thanks

**Comment by walles** [comment] 2021-10-02 14:34
For the first issue, I don't see the upside compared to:
1. Search for `pattern` using `/`
2. Press <kbd>Return</kbd> to exit search mode
3. Press `n` repeatedly until you get to the right place

If you think there's an obvious use case here, can you explain in more detail how the vim way would be an improvement over ^?

For the second issue, is there an answer for you in the Workarounds section of #53?

Third, I'm a person not a team :)

**Comment by ciscohack** [comment] 2021-10-02 17:52
@walles I am currently doing search through / only but with :g/pattern one will able to list only the line matches to searched keyword but with / it will search all the file line by line.

Second alt key is working for me also to copy the selection but in search field i am not able to paste it.

**Comment by walles** [comment] 2021-10-04 04:59
I can confirm that pasting into the search field doesn't work.

Can you open a separate issue for that? I'd like to be able to treat these two issues separately.

**Comment by ciscohack** [comment] 2021-10-04 05:31
Sure and thanks

**Comment by walles** [comment] 2021-10-04 06:22
> @walles I am currently doing search through / only but with :g/pattern one will able to list only the line matches to searched keyword but with / it will search all the file line by line.

I understand what you want, I just don't see how it would be worth any effort on my part.

Do you have a concrete usecase like this (bonus points for attaching the file you are searching ing)?
* I'm searching `x.txt`, see attachment
* I can use <kbd>/</kbd> to search this file for `laestrygon`, but I don't like it because of `$REASON`
* In my case, first listing all hits and then picking a line would be better because of `$REASON2`

**Comment by ciscohack** [comment] 2021-10-04 07:15
> > @walles I am currently doing search through / only but with :g/pattern one will able to list only the line matches to searched keyword but with / it will search all the file line by line.
> 
> I understand what you want, I just don't see how it would be worth any effort on my part.
> 
> Do you have a concrete usecase like this (bonus points for attaching the file you are searching ing)?
> 
> * I'm searching `x.txt`, see attachment
> * I can use / to search this file for `laestrygon`, but I don't like it because of `$REASON`
> * In my case, first listing all hits and then picking a line would be better because of `$REASON2`

File what i am using can't be shared but anyway i used this .g/pattern option and i liked it in some cases where i am just willing to render only lines having my searched pattern match. with / option i have to search then hit N for all occurance. so thought to have both options would be good.  You can close this thread and you can test :g/pattern in any of your file to see the results.

**Comment by walles** [comment] 2021-10-04 08:11
Two suggestions which are not exactly what you're asking for, but at least related:

# List all matches to the console

```
grep pattern file.txt
```

# List all matches in `moar`

```
grep pattern file.txt | moar
```

I will close this thread for now.

**Closed by walles** 2021-10-04 08:11 UTC
