### ISSUE TITLE
arm release not supported on Ubuntu Asahi

### ISSUE THREAD

**Issue by tmeijn** [walles/moar#223] opened 2024-07-09 18:02 UTC
When I run the arm binary from the GitHub release page it does not work for me:

```shell
❯ ./Downloads/moar-v1.24.6-linux-arm --version
-bash: ./Downloads/moar-v1.24.6-linux-arm: cannot execute binary file: Exec format error
```

When I run `go install github.com/walles/moar@latest` the binary works just fine and that is also how I have it currently installed.

I think it's because arm doesn't mean arm64? 🤔 If not, then I would request to also release an arm64 build 😄 .

**Comment by walles** [comment] 2024-07-09 19:46
Sort of a duplicate of #137.

The ideal solution here would be if you could package `moar` for Debian. Then it would show up in all flavors of Ubuntu as well.

I'll make sure `go install github.com/walles/moar@latest` is mentioned in the `README.md`.

Unsure about which binaries I should produce, it would be much better if this was done by package maintainers for different platforms...

So again, the best solution here would be if you could submit `moar` for Debian packaging.

**Comment by walles** [comment] 2024-09-08 05:32
I'll just close this as a duplicate of #137.

Kindly let me know if your Debian package gets accepted.

**Closed by walles** 2024-09-08 05:32 UTC
Labels: help-wanted, debian-packaging
